Review on the admission trial
Uchenna-ibute/Review-project-trial pull request #2
Opened 2022-12-05 21:38 UTC by Uchenna-ibute

Adding html files
Adding css files
Adding acknowledgement to the readme

2022-12-05 21:43 UTC, Uchenna-ibute reviewed
Great work 👍👍
Do try to make the correction mentioned in the comment.

2022-12-05 21:43 UTC, Uchenna-ibute commented on index.html
> +        <a id="tribute-link" href="https://en.wikipedia.org/wiki/Norman_Borlaug" target="_blank">Wikipedia entry</a>
Nice work, i think its better to use class instead of id from line 12-19, because ID are unique for the page, so it's better for identification. Class aren't unique and are supposed to be to group similar style things together.

Said otherwise, if you need to apply something to THAT SPECIFIC div, you should call it by the id, because it will take priority over other CSS styles that may affect it. Classes will allow you to set some common ground in your style so you can use similar fonts or sizes in different kind of elements.

2022-12-05 22:58 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @Uchenna-ibute 👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

**🏮🏮 IMPORTANT NOTE:** 

- [ ] It's not good enough to close/merge PR that has been reviewed and not yet approved PR 👉 https://github.com/Uchenna-ibute/Review-project-trial/pull/1. please always use the initial not yet approved open pull request for all re-reviews unless requested otherwise.

- ✔️ Pull request summary is descriptive
- ✔️ Linters checks are passing

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-05 22:58 UTC, abdulhamiid commented on index.html
> +        <a id="tribute-link" href="https://en.wikipedia.org/wiki/Norman_Borlaug" target="_blank">Wikipedia entry</a>
- [ ] It would be better if we phrased the comments politely, as suggestions instead of orders. For example:

* This is a polite suggestion: *"I think it would be better to use a class instead of id"*
* This reads as an order: *"next time use class instead of id"* 😃

- [ ] As a way to construct our code review in a professional way 👍, let's always include an explanation, a "why", for each requested change. 

- [ ] Please kindly include a reason for your suggested changes 👏

- [ ] Also as you have generalized your comment like `"use class instead of id"`, that is not very clear and easy to understand. 

- [ ] 👉 (It will be good if we can specify the exact HTML tag we are referring to)

- [ ] e.g  `I think it would be better to use a class instead of id` in `<figure id="img-div">`, and then you will state the reason why you have suggested the change 💪.

- [ ] Also, as mentioned in the [project requirements](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/review_your_project.md) please kindly add as many comments as possible and add `a minimum of 2 comments` in the review. (I could see that you only have one comment}


You will definitely find something that could have been done better!

Examples of issues the student may when performing the review:

* Lack of [semantic HTML tags use](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
* Not applying [HTML & CSS best practices correclty](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
* Bugs missed the first time the project was built.

**_[OPTIONAL]_** It will be nice if you use a couple of emojis 🤗 and/or gifs in the review. they make the code review more human-friendly 👽🤖.

2022-12-05 23:45 UTC, Uchenna-ibute reviewed
Great work 👍👍
Do try to make the correction mentioned in the comment.

2022-12-05 23:45 UTC, Uchenna-ibute commented on style.css
> +html {
Optional
I think its a great practice to always remember to add the CSS universal selector
```suggestion
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}
```
This is useful when you want to set a style for of all the elements of an HTML page or for all of the elements within an element of an HTML page.

2022-12-06 00:17 UTC, DuaneDave approved these changes
Hi @Uchenna-ibute 👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅  Good us of GitHub inline comments 💯 
✅ Comments are polite 💯 
✅ Nice response to requested chance 💯 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-06 00:20 UTC, merged